pipeline:

  build:
    image: node:10
    commands:
    - if [ "${CI_COMMIT_BRANCH:0:3}" = "zzz" ]; then echo "skipping zzz build" && exit 777; fi
    - printenv | tee printenv.log
    - ip addr ls
    - npm install -g grunt
    - npm install

  publish:
    image: plugins/ecr
    repo: marketing-site
    registry: 319156457634.dkr.ecr.us-west-2.amazonaws.com
    dockerfile: docker/marketing-site/Dockerfile
    region: us-west-2
    tags: ${CI_COMMIT_SHA:0:8}

  deploy:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: "true"
    chart: ./chart
    release: bg-marketing-${CI_COMMIT_AUTHOR,,}
    values: subdomain=${CI_COMMIT_AUTHOR,,}-marketing-site,hash=${CI_COMMIT_SHA:0:8}
    namespace: ${CI_COMMIT_AUTHOR,,}-marketing
    secrets: [ api_server, kubernetes_token ]

  test:
    image: cypress/base:10
    volumes:
    - /dev/shm:/dev/shm
    commands:
    - printenv | tee printenv.log
    - pwd
    - npm install -f cypress --save-dev
    - SUBDOMAIN=${CI_COMMIT_AUTHOR,,}-marketing-site
    - echo $SUBDOMAIN
    - url=https://$SUBDOMAIN.bitgo-dev.com
    - echo $url
    - attempt_counter=0
    - max_attempts=150 # 150 x 5 = 750 seconds = 12 minutes and 30 seconds
    - while [ 1 = 1 ]
    - do
    - attempt_counter=$(($attempt_counter+1))
    - echo "attempt $attempt_counter to reach ${url}"
    - res=$(curl --silent --head --fail $url | grep HTTP | grep 200 | wc -l)
    - if [ $res = 1 ]
    - then
    - echo "succeed on $attempt_counter attempt to reach url $url"
    - break
    - fi
    - if [ $attempt_counter == $max_attempts ]
    - then
    - echo "failed to reach url $url"
    - exit 1
    - fi
    - sleep 5
    - done
    - export CYPRESS_BASE_URL=$url
    - node_modules/.bin/cypress run


  notify:
    image: drillster/drone-email

    host: smtp.mandrillapp.com
    port: 587
    from: mandrill@bitgo.com
    attachment:
    recipients: [ experience@bitgo.com ]
    subject: >
      Build {{ build.status }} : {{ repo.owner }}/{{ repo.name }} : {{ commit.branch }} - {{ commit.message }} By {{ commit.author.name }}
    body: >
      <h1 style="color:Green;">Status: {{ build.status }}</h1>
      <h3>build initiated by ${DRONE_COMMIT_AUTHOR_EMAIL%@*}</h3>
      <h3>github user name: ${CI_COMMIT_AUTHOR}</h3>
      <h3>github commit link: ${CI_BUILD_LINK}</h3>
      <h3>drone build link: ${DRONE_BUILD_LINK}<h3>
    secrets: [ email_username, email_password ]
    when:
      status: [success]

  notify:
    image: drillster/drone-email

    host: smtp.mandrillapp.com
    port: 587
    from: mandrill@bitgo.com
    attachment:
    recipients: [ experience@bitgo.com ]
    subject: >
      Build {{ build.status }} : {{ repo.owner }}/{{ repo.name }} : {{ commit.branch }} - {{ commit.message }} By {{ commit.author.name }}
    body: >
      <h1 style="color:Red;">Status: {{ build.status }}</h1>
      <h3>build initiated by ${DRONE_COMMIT_AUTHOR_EMAIL%@*}</h3>
      <h3>github user name: ${CI_COMMIT_AUTHOR}</h3>
      <h3>github commit link: ${CI_BUILD_LINK}</h3>
      <h3>drone build link: ${DRONE_BUILD_LINK}<h3>
    secrets: [ email_username, email_password ]
    when:
      status: [changed, failure ]

