pipeline:

  build:
    image: node:10
    commands:
    - if [ "${CI_COMMIT_BRANCH:0:3}" = "zzz" ]; then echo "skipping zzz build" && exit 777; fi
    - printenv | tee printenv.log
    - ip addr ls
    - npm install -g grunt
    - npm install

