version: '3'

services:
  drone-server:
    image: drone/drone:1.0.0-rc.5
    ports:
      - 8000:80

    volumes:
      #guo - /var/lib/drone:/var/lib/drone
      - drone-server-data:/var/lib/drone/

    restart: always
    env_file:
      - /etc/drone/server.env

  drone-agent:
    image: drone/agent:1.0.0-rc.5
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - /etc/drone/agent.env

volumes:
    drone-server-data:
