version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 127.0.0.1:8000:8000
      - 9000:9000
    volumes:
      #guo - /var/lib/drone:/var/lib/drone
      - drone-server-data:/var/lib/drone/

    restart: always
    env_file:
      - /etc/drone/server.env

  drone-agent:
    image: drone/agent:0.8
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - /etc/drone/agent.env

volumes:
    drone-server-data:
